apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-ingress
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: nginx-ingress
  project: {{ .Values.spec.project }}
  source:
    chart: nginx-ingress
    helm:
      parameters:
        - name: "controller.nginxStatus.port"
          value: "9000"
        - name: "controller.nginxStatus.allowCidrs"
          value: "0.0.0.0/0"
        - name: "controller.enableSnippets"
          value: "true"
        - name: "prometheus.create"
          value: "true"
        - name: "serviceInsight.create"
          value: "true"
    repoURL: https://helm.nginx.com/stable
    targetRevision: 0.16.2
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true