apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: default
  project: {{ .Values.spec.project }}
  source:
    path: setup/apps
    repoURL: https://github.com/f5devcentral/modern_app_jumpstart_workshop.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
